<a href="https://colab.research.google.com/github/Vinaysankeerth13/Data_Cleaning_Data_analytics_internship_week3/blob/main/Solution_week3_Dataset_1_Vinay_Sankeerth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import libraries

In [ ]:
import numpy as np
import pandas as pd

## Load data

In [ ]:
data = pd.read_csv("/content/Data-cleaning-for-beginners-using-pandas (1).csv")

- head()
- tail()
- info()
- dtypes()
- describe()
- shape

In [ ]:
data.head()

   Index   Age     Salary  Rating       Location  Established Easy Apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [ ]:
data.tail()

    Index   Age     Salary  Rating       Location  Established Easy Apply
24     24  13.0  $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0  $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN  $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0  $44k-$99k     5.4       India,In         1935         -1
28     28   NaN  $39k-$88k     3.4  Australia Aus         1932         -1

In [ ]:
data.sample(5)

    Index   Age     Salary  Rating       Location  Established Easy Apply
23     23   NaN  $44k-$99k     2.4    New York,Ny         1999       TRUE
11     11  44.0  $10k-$49k     6.7       India,In         2009         -1
14     14  66.0  $44k-$99k     4.0  Australia Aus         2020       TRUE
28     28   NaN  $39k-$88k     3.4  Australia Aus         1932         -1
2       2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1

In [ ]:
data.shape

(29, 7)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        29 non-null     int64
 1   Age          22 non-null     float64
 2   Salary       29 non-null     object
 3   Rating       28 non-null     float64
 4   Location     29 non-null     object
 5   Established  29 non-null     int64
 6   Easy Apply   29 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.7+ KB

7 Missing values in **AGE**
1 Missing Value in **Rating**

In [ ]:
data.isna().sum()

Index          0
Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy Apply     0
dtype: int64

In [ ]:
data.columns

Index(['Index', 'Age', 'Salary', 'Rating', 'Location', 'Established',
       'Easy Apply'],
      dtype='object')

In [ ]:
data.columns = data.columns.str.lower().str.replace(' ','_')

In [ ]:
data.head()

   index   age     salary  rating       location  established easy_apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

# Age

In [ ]:
avg_age = data.age.mean()

In [ ]:
data['age'] = data['age'].fillna(avg_age)
data['age'] = data['age'].round(decimals=1)
data['age']

0     44.0
1     66.0
2     39.0
3     64.0
4     25.0
5     44.0
6     21.0
7     44.0
8     35.0
9     22.0
10    55.0
11    44.0
12    39.0
13    25.0
14    66.0
15    44.0
16    19.0
17    39.0
18    35.0
19    32.0
20    39.0
21    35.0
22    19.0
23    39.0
24    13.0
25    55.0
26    39.0
27    52.0
28    39.0
Name: age, dtype: float64

In [ ]:
data['age'] = data['age'].astype(int)
data['age']

0     44
1     66
2     39
3     64
4     25
5     44
6     21
7     44
8     35
9     22
10    55
11    44
12    39
13    25
14    66
15    44
16    19
17    39
18    35
19    32
20    39
21    35
22    19
23    39
24    13
25    55
26    39
27    52
28    39
Name: age, dtype: int64

In [ ]:
data['age'].isna().sum()

0

# Salary

In [ ]:
data['salary'] = data['salary'].apply(lambda x:x.replace('$',''))

In [ ]:
data['salary']

0      44k-99k
1      55k-66k
2      77k-89k
3      44k-99k
4      44k-99k
5      77k-89k
6      44k-99k
7      44k-99k
8      44k-99k
9      44k-99k
10     10k-49k
11     10k-49k
12     44k-99k
13     44k-99k
14     44k-99k
15    88k-101k
16     19k-40k
17     44k-99k
18     44k-99k
19     44k-99k
20     44k-99k
21     44k-99k
22     55k-66k
23     44k-99k
24     44k-99k
25     44k-99k
26     55k-66k
27     44k-99k
28     39k-88k
Name: salary, dtype: object

In [ ]:
data['salary'] = data['salary'].apply(lambda x:x.replace('k',''))

In [ ]:
data['salary']

0      44-99
1      55-66
2      77-89
3      44-99
4      44-99
5      77-89
6      44-99
7      44-99
8      44-99
9      44-99
10     10-49
11     10-49
12     44-99
13     44-99
14     44-99
15    88-101
16     19-40
17     44-99
18     44-99
19     44-99
20     44-99
21     44-99
22     55-66
23     44-99
24     44-99
25     44-99
26     55-66
27     44-99
28     39-88
Name: salary, dtype: object

# Rating

In [ ]:
rating_avg = data['rating'].mean()
data['rating'] = data['rating'].fillna(rating_avg)
data['rating']

0     5.400000
1     3.500000
2    -1.000000
3     4.400000
4     6.400000
5     1.400000
6     0.000000
7    -1.000000
8     5.400000
9     7.700000
10    5.400000
11    6.700000
12    0.000000
13   -1.000000
14    4.000000
15    3.000000
16    4.500000
17    5.300000
18    6.700000
19    3.300000
20    5.700000
21    5.000000
22    7.800000
23    2.400000
24   -1.000000
25    0.000000
26    3.528571
27    5.400000
28    3.400000
Name: rating, dtype: float64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        29 non-null     int64
 1   age          29 non-null     int64
 2   salary       29 non-null     object
 3   rating       29 non-null     float64
 4   location     29 non-null     object
 5   established  29 non-null     int64
 6   easy_apply   29 non-null     object
dtypes: float64(1), int64(3), object(3)
memory usage: 1.7+ KB

#Location

In [ ]:
data.head()

   index  age salary  rating       location  established easy_apply
0      0   44  44-99     5.4       India,In         1999       TRUE
1      1   66  55-66     3.5    New York,Ny         2002       TRUE
2      2   39  77-89    -1.0    New York,Ny           -1         -1
3      3   64  44-99     4.4       India In         1988         -1
4      4   25  44-99     6.4  Australia Aus         2002         -1

In [ ]:
data['location'] = data['location'].apply(lambda x:x.replace('India,In','India'))
data['location'] = data['location'].apply(lambda x:x.replace('New York,Ny','New York'))
data['location'] = data['location'].apply(lambda x:x.replace('Australia Aus','Australia'))
data['location']

0         India
1      New York
2      New York
3      India In
4     Australia
5         India
6      New York
7     Australia
8      New York
9         India
10        India
11        India
12        India
13    Australia
14    Australia
15    Australia
16        India
17     New York
18     New York
19     New York
20     New York
21     New York
22     New York
23     New York
24     New York
25    Australia
26        India
27        India
28    Australia
Name: location, dtype: object

#Established

In [ ]:
data['established']

0     1999
1     2002
2       -1
3     1988
4     2002
5     1999
6       -1
7       -1
8       -1
9       -1
10    2008
11    2009
12    1999
13    2019
14    2020
15    1999
16    1984
17    1943
18    1954
19    1955
20    1944
21    1946
22    1988
23    1999
24    1987
25    1980
26    1934
27    1935
28    1932
Name: established, dtype: int64

In [ ]:
data['established'] = data['established'].apply(lambda x: x if x > 0 else pd.NA)
data['established']

0     1999
1     2002
2     <NA>
3     1988
4     2002
5     1999
6     <NA>
7     <NA>
8     <NA>
9     <NA>
10    2008
11    2009
12    1999
13    2019
14    2020
15    1999
16    1984
17    1943
18    1954
19    1955
20    1944
21    1946
22    1988
23    1999
24    1987
25    1980
26    1934
27    1935
28    1932
Name: established, dtype: object

#Easy_Apply

In [ ]:

data['easy_apply']

0     TRUE
1     TRUE
2       -1
3       -1
4       -1
5     TRUE
6       -1
7       -1
8       -1
9     TRUE
10    TRUE
11      -1
12      -1
13    TRUE
14    TRUE
15      -1
16      -1
17    TRUE
18    TRUE
19    TRUE
20    TRUE
21      -1
22    TRUE
23    TRUE
24      -1
25    TRUE
26    TRUE
27      -1
28      -1
Name: easy_apply, dtype: object

In [ ]:
data['easy_apply'] = data['easy_apply'].apply(lambda x:x.replace('-1','FALSE'))
data['easy_apply'] = data['easy_apply'].map({'TRUE': True, 'FALSE': False})
data['easy_apply']

0      True
1      True
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9      True
10     True
11    False
12    False
13     True
14     True
15    False
16    False
17     True
18     True
19     True
20     True
21    False
22     True
23     True
24    False
25     True
26     True
27    False
28    False
Name: easy_apply, dtype: bool

#Cleaned Data

Year of Establishment is a unique value so i didn't feel its something we can replace with a computational value.

In [ ]:
data.head()

   index  age salary  rating   location established  easy_apply
0      0   44  44-99     5.4      India        1999        True
1      1   66  55-66     3.5   New York        2002        True
2      2   39  77-89    -1.0   New York        <NA>       False
3      3   64  44-99     4.4   India In        1988       False
4      4   25  44-99     6.4  Australia        2002       False

In [ ]:
data.tail()

    index  age salary    rating   location established  easy_apply
24     24   13  44-99 -1.000000   New York        1987       False
25     25   55  44-99  0.000000  Australia        1980        True
26     26   39  55-66  3.528571      India        1934        True
27     27   52  44-99  5.400000      India        1935       False
28     28   39  39-88  3.400000  Australia        1932       False

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        29 non-null     int64
 1   age          29 non-null     int64
 2   salary       29 non-null     object
 3   rating       29 non-null     float64
 4   location     29 non-null     object
 5   established  24 non-null     object
 6   easy_apply   29 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(3)
memory usage: 1.5+ KB